import { AimsProvider } from "@/context/aims-context";
import { AuthProvider } from "@/context/auth-context";
import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aim Streaker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased font-sans`}
    >
      <body className="flex min-h-full flex-col bg-background">
        {/* Desktop Blocker Overlay */}
        <div className="hidden sm:flex fixed inset-0 z-50 flex-col items-center justify-center bg-black p-6 select-none overflow-hidden">
          {/* Subtle background glow */}
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-accent/10 rounded-full blur-[120px] pointer-events-none" />

          <div className="relative z-10 flex flex-col items-center max-w-sm text-center">
            {/* Phone Silhouette Animation */}
            <div className="relative w-20 h-36 border-4 border-zinc-700 rounded-[2.5rem] p-1.5 mb-8 animate-pulse shadow-[0_0_20px_rgba(163,255,18,0.15)] flex items-center justify-center">
              {/* Notch */}
              <div className="absolute top-0 left-1/2 -translate-x-1/2 w-10 h-3 bg-zinc-700 rounded-b-md" />
              {/* Neon Green Screen Content Mock */}
              <div className="w-full h-full bg-zinc-900/50 rounded-[2rem] flex flex-col items-center justify-center p-2 border border-zinc-800">
                <div className="w-8 h-8 rounded-full border-2 border-accent border-t-transparent animate-spin mb-2" />
                <div className="w-10 h-1.5 bg-accent/40 rounded-full mb-1" />
                <div className="w-6 h-1 bg-zinc-800 rounded-full" />
              </div>
              {/* Home Indicator */}
              <div className="absolute bottom-1 left-1/2 -translate-x-1/2 w-8 h-1 bg-zinc-700 rounded-full" />
            </div>

            {/* Typography */}
            <h1 className="text-3xl font-extrabold tracking-tight text-white mb-3">
              Aim <span className="text-accent">Streaker</span>
            </h1>
            <p className="text-sm font-medium text-zinc-400 mb-8 leading-relaxed">
              This application is optimized for mobile devices to provide the best view and experience. Please open this URL on your phone to continue.
            </p>

          </div>
        </div>

        {/* Mobile Viewport Container */}
        <div className="sm:hidden mx-auto flex min-h-full w-full max-w-[430px] flex-1 flex-col">
          <AuthProvider>
            <AimsProvider>{children}</AimsProvider>
          </AuthProvider>
        </div>
      </body>
    </html >
  );
}
